### ISSUE TITLE
Look through application criteria to determine events to listen to

### ISSUE THREAD

**Issue by RobertHerhold** [BadgeUp/sponge-client#1]
Check if `criteria:read` is in the API key scopes, then go through and determine which events to listen to and post to BUp

**Comment by MarkHerhold** [comment]
Hmmmm. So this would be a way to have client automatically only push events
that they have criteria for? Neat idea!

**Comment by RobertHerhold** [comment]
This won't work because metrics need to stay updated so new achievements can be awarded without starting from 0
