### ISSUE TITLE
Rename config folder/file/plugin id

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#11]
You will only ever run one BadgeUp client on a Minecraft server so calling the plugin badgeup-sponge-client is redundant. A `badgup` config folder/file is simple an too the point. It's just a lot cleaner.

https://github.com/BadgeUp/sponge-client/blob/master/src/main/java/io/badgeup/sponge/BadgeUpSponge.java#L59

**Comment by RobertHerhold** [comment]
I agree - it will be changed shortly
