### ISSUE TITLE
BadgeUp Client/DiscordBridge incompatability

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#13]
BadgeUp: badgeup-sponge-client-v1.1.0
DiscordBridge: [DiscordBridge-2.3.0-all](https://github.com/nguyenquyhy/DiscordBridge/releases)
SF: spongeforge-1.10.2-2221-5.1.0-BETA-2136

Okay this is a weird bug but when I add BadgeUp to my server, DiscordBridge stops working. If I remove BadgeUp, DiscordBridge starts working again. I've never had another plugin conflict with DiscordBridge.

**Comment by MarkHerhold** [comment]
@Mohron Any errors in the logs? What did you do to determine that it had stopped working? Thanks for reporting this!

**Comment by Mohron** [comment]
The discord plugin fails to make connections after saying there's an invalid bot token, which isn't at all the case (plugin connected after removing BadgeUp). DiscordBridge does load after BadgeUp so something it's doing must be affecting other plugins. I can't find anything obvious outside the event errors BadgeUp throws.

[SERVER LOG](https://gist.github.com/Mohron/cb65902824269cebb266e638a206a1f8)

**Comment by Mohron** [comment]
Thanks! I wouldn't have been able to use BadgeUp without this fix.

**Comment by RobertHerhold** [comment]
So basically, this is what was happening:

DiscordBridge uses a library to connect to Discord called Javacord. Javacord uses the same HTTP library (Unirest) that this plugin does. In this plugin, I set the default HTTP client to be configured with headers used in every request. Those headers were somehow being used in the HTTP requests sent by Javacord, preventing the auth request from going through

**Comment by RobertHerhold** [comment]
Released in [v2.0.0](https://github.com/BadgeUp/sponge-client/releases/tag/v2.0.0)

**Comment by Mohron** [comment]
Ya I contribute to the plugin but only features. All connection code is the main dev. Just glad it's fixed :)

**Comment by MarkHerhold** [comment]
@Mohron We appreciate it. 👍 
Keep the issues/feedback coming!
