### ISSUE TITLE
Events with little to no use

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#16]
Obviously use your best judgement here. I know you're already filtering some events out and I have a few that I see being tracked that IMO are not valuable data:

- [x] ChannelRegistration.Register
- [x] TabComplete.Command
- [x] [changeblock:pre](https://github.com/SpongePowered/SpongeAPI/blob/stable-5.1.0/src/main/java/org/spongepowered/api/event/block/ChangeBlockEvent.java#L98)
- [x]  [sleeping:pre](https://github.com/SpongePowered/SpongeAPI/blob/stable-5.1.0/src/main/java/org/spongepowered/api/event/action/SleepingEvent.java#L48), [sleeping:tick](https://github.com/SpongePowered/SpongeAPI/blob/stable-5.1.0/src/main/java/org/spongepowered/api/event/action/SleepingEvent.java#L50), [sleeping:post](https://github.com/SpongePowered/SpongeAPI/blob/stable-5.1.0/src/main/java/org/spongepowered/api/event/action/SleepingEvent.java#L52) - IMO only Finish or post is useful
- [x] [dropitem:pre](https://github.com/SpongePowered/SpongeAPI/blob/stable-5.1.0/src/main/java/org/spongepowered/api/event/item/inventory/DropItemEvent.java#L55)
- [x] [constructentity:pre](https://github.com/SpongePowered/SpongeAPI/blob/stable-5.1.0/src/main/java/org/spongepowered/api/event/entity/ConstructEntityEvent.java#L63)
- [x] changestatistic:targetplayer

_I may add more to this list as I continue my testing._

**Comment by Mohron** [comment]
I've added a few more events (all subinterfaces) that are unlikely to be useful in creating criteria (probably true of most of not all "pre" events as they're intended for early cancellation).

**Comment by RobertHerhold** [comment]
Updated in 2e320cfc2126f87791df0a68cdeef36ddf891ab4
