### ISSUE TITLE
Distance Event Tracking & Commands

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#17]
This is not a bug but this is not likely how your users are going to expect a `distance` criteria to work as it is way too easy to just teleport a few times to complete this criteria.  I would consider making distance traveled by command ignored.

**Comment by RobertHerhold** [comment]
@Mohron I previously had `MoveEntityEvent.Teleport` ignored, but that wouldn't have worked in the case that players move after teleporting. It should be fixed now.
