### ISSUE TITLE
Event too large

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#19]
I get these in my console all the time:

`pool-2-thread-4241/ERROR [badgeup]: Event too large: changeblock:place:minecraft:leaves`

There has to be a better way of handling these events. If they're not able to be tracked at all, it will severely limit the usability of this service for minecraft.

**Comment by MarkHerhold** [comment]
@Mohron I'm 99% sure that we're able to normally place leaves and track that event. I wonder if some other plugins are inflating the event size. We'll look into it.

**Comment by RobertHerhold** [comment]
@Mohron I wasn't able to get any `changeblock:place` events that were too large - in fact, they weren't very big at all. In [v2.0.1](https://github.com/BadgeUp/sponge-client/releases/tag/v2.0.1), the event body is printed out to the debug logs if it is too large. If you see it happen again, please post the event body here so I can try to slim down the event.

**Comment by Mohron** [comment]
https://hastebin.com/anibocagaw.rb this if from SF3 btw

**Comment by RobertHerhold** [comment]
@Mohron Thanks for the logs, I think I have an idea about how to fix it.

**Comment by RobertHerhold** [comment]
@Mohron This (and other issues) are fixed in [v2.0.3](https://github.com/BadgeUp/sponge-client/releases/tag/v2.0.3)
