### ISSUE TITLE
GrantAchievementEvent needs special handling

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#22]
`GrantAchievementEvent` provides nothing valuable on it's own. `GrantAchievementEvent.TargetPlayer` is currently picked up by BadgeUp on 1.11.2 (not implemented on 1.10.2 SF). I recommend that instead of `grantachievement:targetplayer` being sent to BadgeUp, send `grantachievement:<achievement_name>`, like block/item related events currently do. 

Also FYI, `GrantAchievementEvent` is fired every time the achievement could be granted, not only the first time it was earned. I could see use for tracking all and only tracking the original so I'll leave that up to you to decide how to handle.

**Comment by RobertHerhold** [comment]
I released this in [v2.0.7](https://github.com/BadgeUp/sponge-client/releases/tag/v2.0.7)

I also added docs regarding this [here](https://docs.badgeup.io/sponge-client/extending-mc-achievements/).
