### ISSUE TITLE
Create serializer for Transform

### ISSUE THREAD

**Issue by MarkHerhold** [BadgeUp/sponge-client#23]
Right now we get these pretty intense data objects on `abouttoteleport` events:
```
{"ToTransform": "Transform{location=Location{(-3.5, 64.0, -0.5) in WorldServer{LevelName=DIM1, DimensionId=1, DimensionType=minecraft:the_end}}, rotation=(47.84990310668945, -57.59282684326172, 0.0), scale=(1.0, 1.0, 1.0)}", "CancelMessage": "Optional.empty"}
```

**Comment by Mohron** [comment]
That's a Nucleus event. You can filter it. I was trying to not list events that weren't pure Sponge.

**Comment by Mohron** [comment]
https://github.com/NucleusPowered/Nucleus/blob/sponge-api/5/nucleus-api/src/main/java/io/github/nucleuspowered/nucleus/api/events/NucleusTeleportEvent.java

**Comment by MarkHerhold** [comment]
Thanks for the correction!

**Comment by Mohron** [comment]
Transforms are a Sponge object so you may still want to be able to serialize it.

**Comment by Mohron** [comment]
What's the plan to handle events added by other plugins? Nucleus will be common enough that integrating with the Nucleus API would probably be worth your time. Obviously you won't be integrating with every plugin that add events, but even if you could filter non-Sponge events, that wouldn't be preferable either.
