### ISSUE TITLE
Implement Achievement Titles

### ISSUE THREAD

**Issue by MarkHerhold** [BadgeUp/sponge-client#26]
It would be great to be able to add achievement titles and the name of the achievement on the screen when earned.

![image](https://cloud.githubusercontent.com/assets/4934732/25181666/420f0f66-24e0-11e7-9c96-cd05974c5319.png)

https://gyazo.com/f08a208f7e76d3bf658d6e9a006c8497

**Comment by Mohron** [comment]
I approve! Would be a welcomed enhancement. 

There's a Player#sendTitle method I believe.
