### ISSUE TITLE
Error on /badgeup init

### ISSUE THREAD

**Issue by TibTub** [BadgeUp/sponge-client#30]
When running the command /badgeup init (after setting up an API key for Sponge) I'm faced with these error messages:
https://puu.sh/wLCgr/106fc103fb.png
This is the version I'm running:
https://puu.sh/wLCh1/b3178f3c0a.png
And the console shows this:
https://hastebin.com/ihosirobij.md

I've sent an email to the address provided but figure it's good to have a GitHub issue set up for tracking and such :)

EDIT: Wording and correct links.

**Comment by RobertHerhold** [comment]
@TibTub Thanks for reporting this! I fixed this in 17b2732b2131ccb3faa4c17c4b989bc8ca9471f0 and it is now released in [v2.2.3](https://github.com/BadgeUp/badgeup-sponge-client/releases/tag/v2.2.3).
