### ISSUE TITLE
Minecraft/Sponge 1.12

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#31]
GrantAchievementEvent seems to have been removed.

https://hastebin.com/nojeferohi.sql

**Comment by Mohron** [comment]
This is still unusable on a MC 1.12.2 Sponge server

**Comment by RobertHerhold** [comment]
@Mohron I've just updated the plugin to be compatible w/ MC 1.12.2/SpongeAPI 7.0.0

https://github.com/BadgeUp/badgeup-sponge-client/releases/tag/v3.0.0

**Comment by Mohron** [comment]
Thank you for this!
