### ISSUE TITLE
[3.0.0] NPE ItemCraftedEvent

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#33]
This is spamming my console pretty bad so a fix would be much appreciated!

https://hastebin.com/safopavejo.scala

**Comment by RobertHerhold** [comment]
Resolved in 1e4654ac9fc2ca5e063d970f542c688699dfa8d7

v3.0.1 released: https://github.com/BadgeUp/badgeup-sponge-client/releases/tag/v3.0.1
