### ISSUE TITLE
[3.0.0] Could not pass ItemSmeltedEvent

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#34]
Likely unimplemented:

```[16:10:28] [Server thread/ERROR] [Sponge]: Could not pass ItemSmeltedEvent to Plugin{id=badgeup, name=BadgeUp Sponge Client, version=3.0.0, description=Easily add Achievements and Awards to your Sponge server, url=https://www.badgeup.io/, authors=[Robert Herhold], source=/home/container/./plugins/badgeup-sponge-client-v3.0.0.jar}```

**Comment by RobertHerhold** [comment]
Resolved in 1e4654ac9fc2ca5e063d970f542c688699dfa8d7

v3.0.1 released: https://github.com/BadgeUp/badgeup-sponge-client/releases/tag/v3.0.1
