### ISSUE TITLE
Dropping/picking up an ItemStack with more than 1 item only increments the metric by 1

### ISSUE THREAD

**Issue by RobertHerhold** [BadgeUp/sponge-client#7]
It should increment by the quantity of the `ItemStack`

**Comment by Mohron** [comment]
You have two options that I'm aware of here:
- Filter these events from you main listener and make a separate listener (same java class) for the special handling
- Filter out the handling of these events within the main listener using `event instanceof eventClass` to trigger their special handling

**Comment by Mohron** [comment]
You're on a roll, surely you can fix this one!
