### ISSUE TITLE
Command Award

### ISSUE THREAD

**Issue by RobertHerhold** [BadgeUp/sponge-client#8]
Allow users to specify a command to be executed on behalf of the server.

Considerations:
 * Templating engine, to allow different variables to be used in the command

Example:
``` json
{
    "type": "command",
    "command": "/somecommand ${playerName}"
}
```

**Comment by Mohron** [comment]
This is absolutely crutial to my planed usage (advanced rankup system). Are you planning on making this availible soon?

**Comment by RobertHerhold** [comment]
@Mohron 
It will be going out in the next release (probably today or tomorrow)

**Comment by RobertHerhold** [comment]
@Mohron [v1.1.0](https://github.com/BadgeUp/sponge-client/releases/tag/v1.1.0) has support for this now.

**Comment by Mohron** [comment]
@RobertHerhold A demo achievement should be added to showcase this new capability.

**Comment by RobertHerhold** [comment]
@Mohron I actually just [created a demo command award](https://github.com/BadgeUp/sponge-client/blob/master/src/main/java/io/badgeup/sponge/command/executor/BadgeUpInitCommandExecutor.java#L523-L528) and lumped it in with the "Green Thumb" achievement requiring you to plant 10 saplings. The command is `time set day`, which I thought was appropriate for the achievement.
